config/routes.rb
Rails.application.routes.draw do
  root 'pages#ask'
  get 'ask', to: 'pages#ask'
  post 'answer', to: 'pages#answer'
end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def ask
  end
  def answer
    @question = params[:question]
    if @question.end_with?("?")
      @response = "Silly question, get dressed and go to work!"
    elsif @question == "I am going to work"
      @response = "Great!"
    else
      @response = "I don't care, get dressed and go to work!"
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/answer.html.erb
<h1>Your Answer</h1>
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<p>Your question was: <%= @question %></p>
<p>Answer: <%= @response %></p>
<p>
  <a href="<%= ask_path %>">Ask another question</a>
</p>

app/views/pages/ask.html.erb
<%= form_with url: answer_path, method: :post, local: true do %>
  <div>
    <label for="question">Your question:</label>
    <%= text_field_tag :question %>
  </div>
  <div>
    <%= submit_tag "Ask!" %>
  </div>
<% end %>